select
    {{ sha256_key(['source_system_id', 'contract_terms_version_id']) }} as contract_key,
    source_system_id,
    contract_natural_id,
    contract_terms_version_id,
    delivery_point_natural_id,
    customer_natural_id,
    effective_from_utc,
    effective_to_utc,
    effective_to_utc is null as is_current,
    energy_rate_gbp_per_mwh_th,
    sla_penalty_rate_gbp_per_mwh_th,
    currency_code,
    rate_unit,
    terms_status,
    source_revision,
    revision_type,
    published_at_utc,
    approved_at_utc,
    changed_at_utc,
    change_reason_code,
    agreement_reference,
    synthetic_data,
    pipeline_run_id,
    pipeline_evidence_envelope_id,
    pipeline_ingested_at_utc,
    pipeline_raw_object_uri,
    pipeline_raw_object_sha256,
    pipeline_raw_record_locator,
    pipeline_identity_sha256,
    pipeline_payload_sha256
from {{ ref('int_current_contract_terms') }}
