select
    {{ sha256_key(['source_system_id', 'delivery_point_assignment_id']) }}
        as delivery_point_key,
    source_system_id,
    delivery_point_assignment_id,
    delivery_point_natural_id,
    delivery_point_name,
    site_natural_id,
    customer_natural_id,
    service_type,
    assignment_status,
    effective_from_utc,
    effective_to_utc,
    effective_to_utc is null as is_current,
    source_revision,
    revision_type,
    published_at_utc,
    approved_at_utc,
    corrected_at_utc,
    correction_reason_code,
    synthetic_data,
    pipeline_run_id,
    pipeline_evidence_envelope_id,
    pipeline_ingested_at_utc,
    pipeline_raw_object_uri,
    pipeline_raw_object_sha256,
    pipeline_raw_record_locator,
    pipeline_identity_sha256,
    pipeline_payload_sha256
from {{ ref('int_current_delivery_point_assignments') }}
