select
    {{ sha256_key(['source_system_id', 'site_version_id']) }} as site_key,
    source_system_id,
    site_natural_id,
    site_version_id,
    site_name,
    locality,
    postal_area,
    country_code,
    region_code,
    iana_timezone,
    operational_status,
    version_record_status,
    latitude,
    longitude,
    effective_from_utc,
    effective_to_utc,
    effective_to_utc is null as is_current,
    source_revision,
    revision_type,
    published_at_utc,
    approved_at_utc,
    corrected_at_utc,
    correction_reason_code,
    synthetic_data,
    pipeline_run_id,
    pipeline_evidence_envelope_id,
    pipeline_ingested_at_utc,
    pipeline_raw_object_uri,
    pipeline_raw_object_sha256,
    pipeline_raw_record_locator,
    pipeline_identity_sha256,
    pipeline_payload_sha256
from {{ ref('int_current_site_versions') }}
