select
    delivery_interval_key,
    year(reporting_date) * 10000
        + month(reporting_date) * 100
        + day(reporting_date) as date_key,
    {{ sha256_key(['to_iso8601(interval_start_utc)']) }} as interval_key,
    {{ sha256_key(['customer_source_system_id', 'customer_version_id']) }} as customer_key,
    {{ sha256_key(['site_source_system_id', 'site_version_id']) }} as site_key,
    {{ sha256_key([
        'delivery_point_source_system_id',
        'delivery_point_assignment_id'
    ]) }} as delivery_point_key,
    {{ sha256_key(['contract_source_system_id', 'contract_terms_version_id']) }}
        as contract_key,
    {{ sha256_key(['meter_source_system_id', 'meter_assignment_id']) }} as meter_key,
    {{ sha256_key([
        'delivery_measurement_status',
        'commitment_status',
        'normalized_capacity_status',
        'contract_status',
        'customer_access_status',
        'sla_result_status',
        'availability_result_status',
        'financial_result_status',
        'correction_status'
    ]) }} as data_status_key,

    delivery_point_natural_id,
    customer_natural_id,
    site_natural_id,
    contract_natural_id,
    meter_natural_id,
    register_natural_id,
    interval_start_utc,
    interval_end_utc,

    cast(opening_register_mwh_th as decimal(20, 6)) as opening_register_mwh_th,
    cast(closing_register_mwh_th as decimal(20, 6)) as closing_register_mwh_th,
    cast(committed_mwh_th as decimal(20, 6)) as committed_mwh_th,
    cast(delivered_mwh_th as decimal(20, 6)) as delivered_mwh_th,
    cast(delivered_steam_t as decimal(20, 6)) as delivered_steam_t,
    cast(shortfall_mwh_th as decimal(20, 6)) as shortfall_mwh_th,
    cast(excess_mwh_th as decimal(20, 6)) as excess_mwh_th,
    cast(deliverable_capacity_mwh_th as decimal(20, 6)) as deliverable_capacity_mwh_th,
    cast(billable_mwh_th as decimal(20, 6)) as billable_mwh_th,
    cast(gross_earned_revenue_gbp as decimal(38, 12)) as gross_earned_revenue_gbp,
    cast(accrued_sla_penalty_gbp as decimal(38, 12)) as accrued_sla_penalty_gbp,
    cast(net_earned_revenue_gbp as decimal(38, 12)) as net_earned_revenue_gbp,

    cast(approved_extra_mwh_th as decimal(20, 6)) as approved_extra_mwh_th,
    cast(unbilled_excess_mwh_th as decimal(20, 6)) as unbilled_excess_mwh_th,
    cast(sla_attainment_numerator_mwh_th as decimal(20, 6))
        as sla_attainment_numerator_mwh_th,
    cast(contractual_availability_numerator_mwh_th as decimal(20, 6))
        as contractual_availability_numerator_mwh_th,
    expected_interval_count,
    commitment_record_count,
    applicable_interval_count,
    accepted_applicable_delivery_count,
    final_applicable_capacity_count,

    cast(energy_rate_gbp_per_mwh_th as decimal(18, 6))
        as energy_rate_gbp_per_mwh_th,
    cast(sla_penalty_rate_gbp_per_mwh_th as decimal(18, 6))
        as sla_penalty_rate_gbp_per_mwh_th,
    currency_code,
    delivery_measurement_status,
    commitment_status,
    normalized_capacity_status as capacity_status,
    contract_status,
    customer_access_status,
    sla_result_status,
    availability_result_status,
    financial_result_status,
    correction_status,

    coverage_run_count,
    coverage_pipeline_run_ids,
    first_coverage_published_at_utc,
    latest_coverage_published_at_utc,
    coverage_raw_manifest_uris,
    coverage_raw_manifest_sha256s,
    coverage_reconciliation_artifact_uris,
    coverage_reconciliation_artifact_sha256s,

    customer_version_id,
    customer_source_revision,
    customer_published_at_utc,
    customer_approved_at_utc,
    customer_pipeline_payload_sha256,
    site_version_id,
    site_source_revision,
    site_published_at_utc,
    site_approved_at_utc,
    site_pipeline_payload_sha256,
    delivery_point_assignment_id,
    delivery_point_assignment_source_revision,
    delivery_point_assignment_published_at_utc,
    delivery_point_assignment_approved_at_utc,
    delivery_point_assignment_pipeline_payload_sha256,
    contract_terms_version_id,
    contract_source_revision,
    contract_published_at_utc,
    contract_approved_at_utc,
    contract_pipeline_payload_sha256,
    meter_assignment_id,
    meter_assignment_source_revision,
    meter_assignment_published_at_utc,
    meter_assignment_approved_at_utc,
    meter_assignment_pipeline_payload_sha256,
    source_commitment_revision_id,
    commitment_source_revision,
    commitment_published_at_utc,
    commitment_approved_at_utc,
    commitment_pipeline_payload_sha256,
    excess_order_natural_id,
    order_interval_line_id,
    excess_order_source_revision,
    excess_order_published_at_utc,
    excess_order_approved_at_utc,
    excess_order_pipeline_payload_sha256,
    opening_source_reading_revision_id,
    opening_reading_source_revision,
    opening_reading_published_at_utc,
    opening_reading_approved_at_utc,
    opening_reading_pipeline_payload_sha256,
    closing_source_reading_revision_id,
    closing_reading_source_revision,
    closing_reading_published_at_utc,
    closing_reading_approved_at_utc,
    closing_reading_pipeline_payload_sha256,
    source_capacity_revision_id,
    capacity_source_revision,
    capacity_published_at_utc,
    capacity_approved_at_utc,
    capacity_pipeline_payload_sha256
from {{ ref('int_steam_delivery_interval_calculations') }}
